require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'ffbeDataExporterMobile' do
  pod 'GoogleSignIn', '~> 5.0.2'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'ffbeDataExporterMobileTests' do
    inherit! :complete
    # Pods for testing
    pod 'RNFS', :path => '../node_modules/react-native-fs'
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'ffbeDataExporterMobile-tvOS' do
  # Pods for ffbeDataExporterMobile-tvOS

  target 'ffbeDataExporterMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
